# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
	# before_all do
 #  	end

 #  	desc "Runs tests with usage of emulator plugin"
	# lane :automation_integrationTests do
	# 	automated_test_emulator_run(
	# 	  AVD_setup_path: "/Users/pgl/AndroidStudioProjects/DevOpsDemoAndroid/AVD_config.json",
	# 	  gradle_task: "connectedAndroidTest"
	# 	)
	# end

	# after_all do |lane|
	# end

	# error do |lane, exception|
	# end

	desc "Running instrumented_tests"
	lane :inst_test do
	  instrumented_tests
	end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
